# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_teacher',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
