# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170421_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='send_id',
            new_name='user',
        ),
    ]
