# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('0', '所有'), ('1', '一班'), ('2', '二班'), ('3', '三班')], max_length=1)),
                ('code', models.CharField(max_length=8)),
                ('time', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
