# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170510_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_file',
            name='comments',
        ),
    ]
