# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_userprofile_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
